name: buildingblocks
on: workflow_dispatch
jobs:
  echohello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
  echogoodbye:
    runs-on: ubuntu-latest
    steps:
      - name: echo fail
        run: |
            echo "I am success and going to exit with 0"
            exit 0         
      - name: Echo Goodbye World
        run: echo "Goodbye World"